179: firmware upgrade
Buckitup-chat/platform pull request #50
Opened 2023-07-31 09:30 UTC by sviatosluv

2023-07-31 10:31 UTC, sergey-lukianov requested changes

2023-07-31 10:31 UTC, sergey-lukianov commented on lib/platform/chat_bridge/logic.ex
> +    end
move into `Platform.Tools.FwUp`

2023-08-15 22:36 UTC, sviatosluv commented on lib/platform/chat_bridge/logic.ex
> +    end
done

2023-08-16 07:44 UTC, sergey-lukianov approved these changes

2023-08-16 10:08 UTC, merged