454: unmount after final sync
Buckitup-chat/platform pull request #58
Opened 2023-08-22 07:53 UTC by sviatosluv

2023-08-22 08:00 UTC, sergey-lukianov requested changes

2023-08-22 08:00 UTC, sergey-lukianov commented on lib/platform/app/media/helpers.ex
> +    |> Supervisor.terminate_child(Platform.App.MediaStages.Healing)
hard coupling on `MediaStages.Healing`

we should take all children of `Media.Supervisor` and terminate them

2023-08-22 20:58 UTC, sviatosluv commented on lib/platform/app/media/helpers.ex
> +    |> Supervisor.terminate_child(Platform.App.MediaStages.Healing)
@sergey-lukianov 
now it terminates every child that starts with `Platform.App.MediaStages` namespace

2023-08-23 12:01 UTC, sergey-lukianov approved these changes

2023-08-23 12:01 UTC, merged