fix: wifi password in hex
Buckitup-chat/platform pull request #96
Opened 2024-02-26 09:17 UTC by roman-khomenko-dev

[Get platform wifi password from application vintage net configuration

2024-02-26 19:44 UTC, sergey-lukianov commented on lib/platform/chat_bridge/wifi.ex
> +    end)
Enum.find?

2024-02-27 09:27 UTC, roman-khomenko-dev commented on lib/platform/chat_bridge/wifi.ex
> +    end)
yes

2024-02-27 15:21 UTC, sergey-lukianov requested changes

2024-02-27 15:21 UTC, sergey-lukianov commented on lib/platform/chat_bridge/wifi.ex
> +    end
```suggestion
    Enum.find_value(configs, {:error, :not_found}, fn
      {^iface, config} -> {:ok, config}
      _ -> false
    end)
```

2024-02-29 05:48 UTC, merged